### ISSUE TITLE
Remove Empty Certification from Portfolio Section

### ISSUE THREAD

**Issue by Keerat666** [jasleen101010/jasleen101010.github.io#2]
<img width="817" alt="image" src="https://user-images.githubusercontent.com/18071315/187095380-fbd840c9-52be-458e-8b70-c7fa43eb51d0.png">

**Comment by jasleen101010** [comment]
@Keerat666 This redirects to my Certifications on LinkedIn! Should I still remove it?

**Comment by jasleen101010** [comment]
Fixed
